src/main/java/se/sundsvall/smloader/integration/openeexternalsoap/OpenEExternalSoapClient.java, src/main/java/se/sundsvall/smloader/integration/openeinternalsoap/OpenEInternalSoapClient.java, src/main/java/se/sundsvall/smloader/integration/openemapper/proposal/Proposal.java, src/main/java/se/sundsvall/smloader/integration/openemapper/proposal/ProposalMapper.java, src/main/java/se/sundsvall/smloader/integration/openemapper/providefeedback/ProvideFeedback.java, src/main/java/se/sundsvall/smloader/integration/openemapper/providefeedback/ProvideFeedbackMapper.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/main/java/se/sundsvall/smloader/service/OpenEService.java, src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/main/resources/application-junit.yml, src/test/java/se/sundsvall/smloader/integration/openemapper/proposal/ProposalMapperTest.java, src/test/java/se/sundsvall/smloader/integration/util/ErrandConstantsTest.java, src/test/java/se/sundsvall/smloader/service/OpenEServiceTest.java, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java, src/test/resources/open-e/flow-instance-sundsvallsforslaget.xml
Added mapping of proposal and added confirm of delivery call to OpenE,
=> Uf 8968 add mapping of proposal

pom.xml, src/integration-test/java/se/sundsvall/smloader/apptest/JobsIT.java, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/api-gateway-token.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/api-messaging-email.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/api-messaging-slack.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/api-support-management-create-fail.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mocks/support-management-errand.json, src/main/java/se/sundsvall/smloader/integration/messaging/MessagingClient.java, src/main/java/se/sundsvall/smloader/integration/messaging/configuration/MessagingConfiguration.java, src/main/java/se/sundsvall/smloader/integration/messaging/configuration/MessagingProperties.java, src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPension.java, src/main/java/se/sundsvall/smloader/service/OpenEService.java, src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/main/java/se/sundsvall/smloader/service/mapper/MessagingMapper.java, src/main/resources/application-it.yml, src/main/resources/application-junit.yml, src/main/resources/application.yml, src/main/resources/integrations/rest/messaging-api.yaml, src/test/java/se/sundsvall/smloader/integration/messaging/configuration/MessagingConfigurationTest.java, src/test/java/se/sundsvall/smloader/integration/messaging/configuration/MessagingPropertiesTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProviderTest.java, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java, src/test/java/se/sundsvall/smloader/service/mapper/MessagingMapperTest.java, src/test/resources/open-e/flow-instance-kontakt-lon-pension.xml
=> UF-9886: Send notification when fail

src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPension.java, src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrder.java, src/main/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSick.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChange.java, src/main/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManager.java, src/main/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWork.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProvider.java, src/test/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProviderTest.java, src/test/resources/open-e/flow-instance-25-pa-jobbet.xml, src/test/resources/open-e/flow-instance-anmal-franvaro.xml, src/test/resources/open-e/flow-instance-kontakt-lon-pension-chef.xml, src/test/resources/open-e/flow-instance-kontakt-lon-pension.xml, src/test/resources/open-e/flow-instance-lonevaxling.xml, src/test/resources/open-e/flow-instance-ny-behorighet.xml
=> UF-10259: Adapted to changes in OeP services

src/main/java/se/sundsvall/smloader/integration/openemapper/OpenEMapperProperties.java, src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProvider.java, src/main/resources/application-it.yml, src/main/resources/application-junit.yml, src/test/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProviderTest.java
=> UF-10249: Added label to properties and updated categories and types.

src/integration-test/resources/JobsIT/__files/test02_export/mappings/api-support-management-create.json, src/integration-test/resources/JobsIT/__files/test02_export/mappings/api-support-management-get.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/api-support-management-create-fail.json, src/main/java/se/sundsvall/smloader/integration/supportmanagement/SupportManagementClient.java, src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/main/resources/integrations/rest/supportmanagement-api.yaml, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java
=> UF-9754: Changed to v8.1 of SupportManagement

src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/api-messaging-email.json, src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/main/java/se/sundsvall/smloader/service/mapper/MessagingMapper.java, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java, src/test/java/se/sundsvall/smloader/service/mapper/MessagingMapperTest.java
=> UF-10332: Added environment to error mail

src/main/java/se/sundsvall/smloader/integration/openemapper/OpenEMapperProperties.java, src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProvider.java, src/main/resources/application-it.yml, src/main/resources/application-junit.yml, src/test/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProviderTest.java
=> UF-10507: Corrected labels

src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemployment.java, src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapper.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapperTest.java, src/test/resources/open-e/flow-instance-foretradesratt-ateranstallning.xml
=> UF-10667: Added salary-type to precedence of reemployment

src/integration-test/resources/JobsIT/__files/test02_export/mappings/api-support-management-create.json, src/integration-test/resources/JobsIT/__files/test02_export/mocks/support-management-errand.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/api-support-management-create-fail.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mocks/support-management-errand.json, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/util/ErrandConstantsTest.java
=> UF-10757: Update mapping constants for ROLE

src/main/java/se/sundsvall/smloader/integration/openemapper/attachment/Attachment.java, src/main/java/se/sundsvall/smloader/integration/openemapper/attachment/AttachmentMultiPartFile.java, src/main/java/se/sundsvall/smloader/integration/supportmanagement/SupportManagementClient.java, src/main/java/se/sundsvall/smloader/service/AttachmentService.java, src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/test/java/se/sundsvall/smloader/integration/openemapper/attachment/AttachmentMultiPartFileTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/attachment/AttachmentTest.java, src/test/java/se/sundsvall/smloader/service/AttachmentServiceTest.java, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java
=> UF-10847: Export attachments to supportManagement

src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapper.java, src/main/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProvider.java, src/test/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapperTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProviderTest.java
=> UF-10880: Add labels to all types of Salary and Pension errands

src/main/java/se/sundsvall/smloader/service/AttachmentService.java, src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/test/java/se/sundsvall/smloader/service/AttachmentServiceTest.java, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java
=> UF-10852: Error handling if attachment was not possible to be saved

src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemployment.java, src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapper.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapperTest.java, src/test/resources/open-e/flow-instance-foretradesratt-ateranstallning.xml
=> Draken-578: Changed mapping of PrecedenceOfReemployment

src/integration-test/resources/JobsIT/__files/test02_export/mappings/api-open-e-get-file.json, src/main/java/se/sundsvall/smloader/integration/openeexternal/OpenEExternalClient.java, src/main/java/se/sundsvall/smloader/integration/openeinternal/OpenEInternalClient.java
=> UF-XYZ: Fixed a faulty path

src/main/java/se/sundsvall/smloader/integration/supportmanagement/SupportManagementClient.java
=> UF-ZYX: MultipartFile should be Requestpart not requestBody

pom.xml, src/integration-test/resources/JobsIT/__files/test02_export/mappings/api-open-e-get-file.json, src/main/java/se/sundsvall/smloader/integration/openeexternal/OpenEExternalClient.java, src/main/java/se/sundsvall/smloader/integration/openeinternal/OpenEInternalClient.java, src/main/java/se/sundsvall/smloader/integration/openemapper/attachment/AttachmentMultiPartFile.java, src/main/java/se/sundsvall/smloader/service/AttachmentService.java, src/main/java/se/sundsvall/smloader/service/OpenEService.java, src/test/java/se/sundsvall/smloader/integration/openemapper/attachment/AttachmentMultiPartFileTest.java, src/test/java/se/sundsvall/smloader/service/AttachmentServiceTest.java, src/test/java/se/sundsvall/smloader/service/OpenEServiceTest.java
=> UF-10848: Handle files as inputstream instead of byte array

src/integration-test/resources/JobsIT/__files/test02_export/mappings/api-support-management-create.json, src/integration-test/resources/JobsIT/__files/test02_export/mocks/support-management-errand.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/api-support-management-create-fail.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mocks/support-management-errand.json, src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapper.java, src/main/java/se/sundsvall/smloader/integration/openemapper/proposal/ProposalMapper.java, src/main/java/se/sundsvall/smloader/integration/openemapper/providefeedback/ProvideFeedbackMapper.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProvider.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapperTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/proposal/ProposalMapperTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/providefeedback/ProvideFeedbackMapperTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProviderTest.java
=> UF-11008: Added familyId to SM errand

src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProvider.java, src/main/java/se/sundsvall/smloader/service/mapper/SupportManagementMapper.java, src/test/java/se/sundsvall/smloader/service/mapper/SupportManagementMapperTest.java
=> UF-11220: Fix NPE-issue

src/main/java/se/sundsvall/smloader/integration/party/PartyClient.java, src/main/java/se/sundsvall/smloader/integration/supportmanagement/SupportManagementClient.java
=> UF-11228: Fixed bad content type negotiation

src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/service/OpenEService.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java, src/test/java/se/sundsvall/smloader/service/OpenEServiceTest.java
=> UF-11254: Refactored fetching of OeP errandId:s for not interupt when exception

src/main/java/se/sundsvall/smloader/integration/messaging/MessagingClient.java, src/main/java/se/sundsvall/smloader/integration/party/PartyClient.java, src/main/java/se/sundsvall/smloader/integration/supportmanagement/SupportManagementClient.java
=> UF-11348: Add Circuitbreakers

pom.xml, src/main/java/se/sundsvall/smloader/api/JobsResource.java
=> UF-11477: Fix intermittent build issue

src/main/java/se/sundsvall/smloader/integration/db/model/CaseEntity.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProviderTest.java
=> draken-794: Changed display-name of sendDigital in employers certificate

src/integration-test/resources/JobsIT/__files/test02_export/mappings/failed-api-support-management-find.json, src/integration-test/resources/JobsIT/__files/test02_export/mappings/pending-api-support-management-find.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/failed-api-support-management-find.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/pending-api-support-management-find.json, src/integration-test/resources/JobsIT/__files/test05_export_when_errand_exists/mappings/failed-api-support-management-find.json, src/integration-test/resources/JobsIT/__files/test05_export_when_errand_exists/mappings/pending-api-support-management-find.json, src/integration-test/resources/JobsIT/__files/test06_export_when_attachment_exists/mappings/failed-api-support-management-find.json, src/integration-test/resources/JobsIT/__files/test06_export_when_attachment_exists/mappings/pending-api-support-management-find.json, src/main/java/se/sundsvall/smloader/integration/supportmanagement/SupportManagementClient.java
=> UF-11248: Fix bug in supporManagementClient

src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java
=> UF-11647: Avoid re-reporting previously failed cases

pom.xml
=> UF-11792: remove redudant dependency

src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProvider.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProviderTest.java, src/test/resources/open-e/flow-instance-kontakt-lon-pension-no-subject.xml
=> UF-11822: Added default-value to title in errand

src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapper.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProvider.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapperTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProviderTest.java, src/test/resources/open-e/flow-instance-ny-behorighet.xml
=> UF-13875: Changed order of parameters and fixed bugs of draken-963 errand

src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/main/resources/integrations/rest/supportmanagement-api.yaml, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java
=> UF-14368: Changed to SM v9.2 and added groups in report sick mapping

src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapperTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java
=> UF-14419: Changed display names

README.md
=> UF-11135: Add readme

src/main/resources/integrations/rest/messaging-api.yaml
=> UF-14633: Update to messaging 6.1

src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPension.java, src/main/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificate.java, src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrder.java, src/main/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemployment.java, src/main/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapper.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSick.java, src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChange.java, src/main/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManager.java, src/main/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProvider.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWork.java, src/main/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProvider.java, src/test/java/se/sundsvall/smloader/integration/openemapper/contactsalaryandpension/ContactSalaryAndPensionProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/permissionorder/PermissionOrderProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/precedenceofreemployment/PrecedenceOfReemploymentMapperTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/salarychange/SalaryChangeProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/substitutemanager/SubstituteManagerProviderTest.java, src/test/java/se/sundsvall/smloader/integration/openemapper/twentyfiveatwork/TwentyFiveAtWorkProviderTest.java
=> Draken-756: Removed stakeholder contact person from LoP errands

src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProvider.java, src/test/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProviderTest.java
=> UF-14824: Add exception handling to EmployersCertificateProvider

src/main/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProvider.java, src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/main/java/se/sundsvall/smloader/service/ThrowingFunction.java, src/test/java/se/sundsvall/smloader/integration/openemapper/employerscertificate/EmployersCertificateProviderTest.java, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java
=> UF-14826: Add handling for exceptions in OpenE mappers

src/main/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProvider.java, src/main/java/se/sundsvall/smloader/integration/util/ErrandConstants.java, src/test/java/se/sundsvall/smloader/integration/openemapper/reportsick/ReportSickProviderTest.java, src/test/resources/open-e/flow-instance-anmal-franvaro.xml
=> Draken-1073: Added mapping of TimeCare and CurrentSchedule

src/integration-test/resources/JobsIT/__files/test02_export/mappings/failed-api-support-management-create.json, src/integration-test/resources/JobsIT/__files/test02_export/mappings/pending-api-support-management-create.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/failed-api-support-management-create-fail.json, src/integration-test/resources/JobsIT/__files/test04_export_when_fail/mappings/pending-api-support-management-create-fail.json, src/main/java/se/sundsvall/smloader/service/SupportManagementService.java, src/test/java/se/sundsvall/smloader/service/SupportManagementServiceTest.java
=> UF-15259: Fix for not setting activeNotification in SM-errand

src/main/java/se/sundsvall/smloader/service/OpenEService.java, src/test/java/se/sundsvall/smloader/service/OpenEServiceTest.java
=> UF-16722: Format datestring

src/integration-test/resources/JobsIT/__files/test01_import/mappings/api-oep-integrator-get-cases-by-familyId-121.json, src/integration-test/resources/JobsIT/__files/test01_import/mappings/api-oep-integrator-get-cases-by-familyId-161.json, src/main/java/se/sundsvall/smloader/service/OpenEService.java, src/test/java/se/sundsvall/smloader/service/OpenEServiceTest.java
=> UF-16722: Format datestring correctly

src/main/java/se/sundsvall/smloader/service/mapper/CaseMapper.java, src/test/java/se/sundsvall/smloader/service/OpenEServiceTest.java, src/test/java/se/sundsvall/smloader/service/mapper/CaseMapperTest.java
=> UF-16724: base64 encode payload

src/main/java/se/sundsvall/smloader/integration/openemapper/orderingrecruitmentsupport/OrderingRecruitmentSupportProvider.java, src/test/java/se/sundsvall/smloader/integration/openemapper/orderingrecruitmentsupport/OrderingRecruitmentSupportProviderTest.java
=> DRAKEN-1617: Changed title of OrderingRecruitmentSupport errands

src/main/java/se/sundsvall/smloader/integration/openemapper/orderingrecruitmentsupport/OrderingRecruitmentSupportProvider.java, src/test/java/se/sundsvall/smloader/integration/openemapper/orderingrecruitmentsupport/OrderingRecruitmentSupportProviderTest.java, src/test/resources/open-e/flow-instance-rekryteringsstod-tidsbegransad.xml, src/test/resources/open-e/flow-instance-rekryteringsstod.xml
=> DRAKEN-1617: Fix for setting title of SM errand
